### PR TITLE
Add CollectionView support

### LINKED ISSUE #258: Add support for CollectionView
I decided to add item to discuss challenges and approaches to implement CollectionView.
I can see two issues straight away - supporting ItemsSource property and ItemTemplate property.

Supporting ItemsSource property was discussed in https://github.com/xamarin/MobileBlazorBindings/issues/249, and I think same approach with wrapping in delegate should work here as well.
The only thing - I'm not sure whether we should do anything about notifying about updates.

Supporting DataTemplate properties will probably be trickier. 
Unlike original Xamarin control, I suggest to make CollectionView in MBB generic where T is item type, and to make ItemTemplate property of `RenderFragment<T>` type.
Smth like this
```csharp
public class CollectionView<T> : ...
{
	[Parameter] public IEnumerable<T> ItemsSource {get; set;}
	[Parameter] public RenderFragment<T> ItemTemplate {get; set;}
...
}
```

So that it could be used like that:
```razor
<CollectionView ItemsSource="_models">
    <ItemTemplate>
        <Label Text="@context.Name" />
    </ItemTemplate>
</CollectionView>

@code {
    List<MyModel> _models;
}
```

Now we need render those items, and pass to Xamarin's ColectionView.

Currently there is no way to render components as root elements, we can only render it as child component (e.g. for Application or ContentPage). Is there an easy way to allow that?
Otherwise I suppose we can create "fake" container element, which we'll simply use to render elements to, and then grab them from it.

As for passing to CollectionView, I suppose we can inherit from `DataTemplateSelector`, smth like this:
```csharp
public class RenderFragmentDataTemplateSelector<T>: DataTemplateSelector
{
	public RenderFragmentDataTemplateSelector(RenderFragment<T> fragment)


	protected override DataTemplate OnSelectTemplate(object item, BindableObject container)
	{
		return _renderer.RenderFragment(fragment((T)item));
	}
}
```

Any thoughts?

### PR DESCRIPTION
**Pull request by Dreamescaper**
Fixes #258 .

This PR is based on #343 , therefore that PR should be reviewed first. Reviewing commit-by-commit might be easier.
<details>
<summary>Example .razor</summary>

```razor
<ContentPage Title="Infinite scroll">
    <StackLayout>
        <CollectionView ItemsSource="_intItems"
                        RemainingItemsThreshold="2"
                        OnRemainingItemsThresholdReached="LoadItems">
            <Header>
                <Label Text="Scroll to load more items." />
            </Header>

            <ItemTemplate>
                <Item Value="@context" />
            </ItemTemplate>

            <Footer>
                <ActivityIndicator IsRunning="_loading" />
            </Footer>
        </CollectionView>
    </StackLayout>
</ContentPage>

@code {
    ObservableCollection<int> _intItems = new ObservableCollection<int>(Enumerable.Range(1, 20));
    bool _loading;

    async Task LoadItems()
    {
    ...
    }
}
```

</details>

<details>
<summary>Screen</summary>

slDDeWRlim

</details>

The main challenge with CollectionView is to add support for DataTemplates (represented by RenderFragment<T> in Blazor).

Small recap how CollectionView works. Using provided DataTemplate it creates enough items to fill the screen (e.g. 20). When the user scrolls the view, it reuses the same items, but updates bindings on those items to reflect other values.

Blazor does not expose any metadata for RenderFragment<T> (in fact, there is no metadata at all, RenderFragment is simply a delegate), and we cannot use XF's bindings to update displayed values directly. Therefore, I use Blazor itself to update those values.
General idea is that I render all the items created by the CollectionView (those 20 ones) to the Blazor tree. Each item is wrapped in ContentView. When CollectionView updates the ContentView's BindingContext, I update Blazor component based on this value.

The most interesting types here:
- MbbDataTemplate\<T\>
DataTemplate, which creates items, handled by Blazor.
Problem is that I cannot return actual items rendered by Blazor - because Blazor works asynchronously. Therefore I create parent ContentView element, set it as a parent for Blazor component, and return it. Actual ChildContent is populated asynchronously.

- DataTemplateItemsComponent\<T\>
This component has method Add (used by MbbDataTemplate) to add Blazor component with provided ContentView parent. And DataTemplateItemsComponent\<T\> renders a DataTemplateItemComponent\<T\> per each ContentView element in a loop.
Therefore, each time when CollectionView creates a new element from a MbbDataTemplate, this component renders additional DataTemplateItemComponent\<T\>.

- DataTemplateItemComponent\<T\>
This component holds provided RenderFragment\<T\> template. It accepts parent ContentView element, subscribes to BindingContextChanged event, and updates elements based on BindingContextValue.
Note that this component only renders anything when BindingContext is not null. I did that to avoid unnecessary updates (CollectionView sets BindingContext to null before changing it to other value for some reason), and because I wanted to avoid the requirement to handle nulls in RenderFragment\<T\> even when all items provided are not null.

- InitializedContentView
Our regular ContentView is lazy, meaning that actual XF element is created only when rendering happens (which is async). That doesn't work here, as I need to return ContentView synchronously. This component accepts XF.ContentView element as a parameter, which allows to pass already created (in MbbDataTemplate) element here.

- DataTemplatePropertyHandler
This handler creates MbbDataTemplate using rendered DataTemplateItemsComponent, and sets it to parent's property (in our case, to CollectionView.ItemTemplate).

InitializedContentViewHandler and DataTemplatePropertyHandler handlers require a reference to a Blazor component, therefore I updated NativeComponentAdapter to allow that.

### CODE REVIEW

**Comment by Dreamescaper** [comment]
I've updated Xaminals sample to use CollectionView (and fixed an issue with icons).
When I increased quantity of items to 1000, I started seeing noticeable stuttering during fast scrolling. However, simply using FFImageLoading rendered resolved it completely for me, so I suppose that's Image issue.

I've also added couple of playground pages to ControlGallery sample (Adding/Removing items, GridLayout, Infinite scroll, MultiSelection).
Page itself opens a bit slow, but I suppose that's due to TabbedPage view limitations.

Note that I wasn't able to test it on iOS or MacOS devices, so let me know if anything's wrong there.

**Comment by Dreamescaper** [comment]
Known issues, which I decided not to tackle in this PR.
(Will log a separate issue with those once merged)

for DataTemplate support

- It is possible to create DataTemplate from RenderFragment\<T\> only, and it _requires_ a BindingContext to be set. 
I plan to add support for RenderFragment (non-generic), which doesn't require BindingContext later.

- Null items are not supported at this point.
As I mentioned, I decided not to support nulls at this point. I did that to avoid unnecessary updates (CollectionView sets BindingContext to null before changing it to other value for some reason), and because I wanted to avoid the requirement to handle nulls in RenderFragment<T> even when all items provided are not null.

- Every element created via MbbDataTemplate has additional ContextView parent. Sometimes that's OK, but probably not always.
Have no idea how to avoid that.

- Can't use this approach for ShellContent.ContentTemplate.
That's a specific case of the previous item. In this case created element should be Page. But in our case it is wrapped in ContentView, which doesn't work here.
Maybe it would be possible to handle this properly in different way, not sure.


for CollectionView

- Grouping is not supported
Because CollectionView\<T\> is a generic component, it is not possible to set ItemsSource to some Groupping\<T\> type. I suppose I could simply define a separate property (e.g. GrouppedItemsSource) for this purpose.

- ItemsSource should be an ObservableCollection if you need to handle items addition/removal.
We need that since items are managed outside of Blazor. That's not really a Blazor way though.
Maybe it's possible to use some kind of wrapper, and calculate diffs between updates, not sure.

- SelectedItems property has `object` type.
I cannot simply cast IList<object> to IList<T>. And I cannot simply invoke .Cast<T>().ToList(), because that leads to an infinite loop if property is binded.

- SelectedItem property has `object` type.
Slightly different issue here. T can be both class and struct. OTOH, SelectedItem is nullable. I don't know how to declare a nullable type which would work in generic context without constraints.

- Templated Header/Footer/Empty view are not supported.
Decided to implement separately.

**Comment by Eilon** [comment]
Hi @Dreamescaper thank you for this PR! I've been super busy with the .NET 6 work to productize BlazorWebView for WPF, WinForms, and .NET MAUI. We're up against some .NET deadlines, which unfortunately means that MBB work has to wait just a little bit. Once the main .NET 6 work is done for .NET MAUI, I will get right back to these PRs!

**Comment by Dreamescaper** [comment]
@Eilon 
Sure!
Thanks for letting know!

**Comment by Eilon** [comment]
Thank you for understanding! I'm always looking forward to looking at your PRs, I just need to find the time!

**Comment by PhilippElhaus** [comment]
Is this related to the "Picker" Control?
I'm searching desparately for a solution to get the Picker control working in MBB. Wasn't able to just wrap it. Is this PR useable for that purpose?

**Comment by Dreamescaper** [comment]
@PhilippElhaus 
Picker control was merged in this PR:
https://github.com/dotnet/MobileBlazorBindings/pull/275

It's not yet released to Nuget, but you can use nightly source.

**Comment by PhilippElhaus** [comment]
Ohh super cool ;D

Thanks a lot !

Mit freundlichen Grüßen,

Philipp Elhaus

**Pull request merged**
