### PR TITLE
Perform Shell navigation before OnInitialyzedAsync completes

### LINKED ISSUE #300: Shell navigation does not happen until OnInitialyzedAsync fully executed
STR:
1. Create Page component with @page directive.
2. Override OnInitializedAsync, put `await Task.Delay(10000);` there.
3. Use ShellNavigationManager to navigate to this page component.

ER: 
Navigation happens immediately. Page is re-rendered after 10s, when OnInitializedAsync is executed.

AR:
Navigation only happens after 10 seconds.

### PR DESCRIPTION
**Pull request by Dreamescaper**
Fixes #300 .

As discussed it the item, in this PR I perform Shell navigation as soon as any Page element is added to the RootContainerHandler (instead of waiting the whole rendering to complete).

### CODE REVIEW

**Comment by Dreamescaper** [comment]
@Eilon 
Could you take a look at this one when you have time?
Sorry for bothering, it just causes me a bit of pain)

**Comment by Eilon** [comment]
@Dreamescaper yes sure thing! I'm working on the Picker PR, which should be ready soon, and then this one is next!

**Comment by Eilon** [comment]
Confirmed that this works now as expected (and verified that the bug reproed without the change). Thank you @Dreamescaper !

BTW sorry for the delay, I was working on some build issues that came up when this repo moved to the 'dotnet' GitHub org. I _hope_ it's now resolved so that we can get a build with your changes out soon!

**Comment by Dreamescaper** [comment]
No worries, thanks a lot!

**Comment by Eilon** [comment]
The build succeeded, so the nightly feed should have the packages that unblock you now!

**Comment by Dreamescaper** [comment]
Hopefully this commit is a lucky one :)
image

**Comment by Eilon** [comment]
Oh boy... 😁

**Pull request merged**
