### PR TITLE
Update MBB to use MAUI

### PR DESCRIPTION
**Pull request by Dreamescaper**
#352 

This PR is based on the other PRs, so they should be reviewed first: #388, #395, #345, #346, #343, #369, #392, #425, #419.

Now, I'm not sure how this PR should be handled. Should it go to some separate branch? Maybe even other repo? 

- [x] Update ComponentWrapperGenerator to generate MAUI wrapper
- [x] Update MobileBlazorBindings to use MAUI
- [x] Rework Xaminals sample to use single project, MAUI, and updated MBB
- [x] Test it on Windows
- [ ] Test it on Mac
- [x] Test it on iOS
- [ ] Rework other samples
- [x] Update templates
- [x] Update the project to use MAUI's BlazorWebView

(I've logged a couple of MAUI bugs when working on this one: 
https://github.com/dotnet/maui/issues/2623, https://github.com/dotnet/maui/issues/2601, https://github.com/dotnet/maui/issues/2600, https://github.com/dotnet/maui/issues/2591, https://github.com/dotnet/maui/issues/2958, https://github.com/dotnet/maui/issues/4729, https://github.com/dotnet/maui/issues/4765
)

### CODE REVIEW

**Comment by Dreamescaper** [comment]
<details>
<summary>recording</summary>

aBYT8qIQCx

</details>

**Comment by Eilon** [comment]
Oh BOY!

**Comment by Dreamescaper** [comment]
Seems like iOS support is blocked by this bug:
https://github.com/dotnet/maui/issues/3536

**Comment by Eilon** [comment]
Looks pretty nice!

image

To work around some of the build issues I temporarily changed `src\Microsoft.MobileBlazorBindings\Microsoft.MobileBlazorBindings.csproj` to use `<Project Sdk="Microsoft.NET.Sdk.Razor">` so that the various Static Web Assets targets are available.

We might just have to get this merged with some workaround (and we'll log bugs to un-do those workarounds) because it might be a while until we can get the real fixes in .NET MAUI.

**Comment by Dreamescaper** [comment]
@Eilon 
Yeah, originally I had `Sdk="Microsoft.NET.Sdk.Razor"`, but it breaks iOS samples completely, they don't even compile.
So I wanted to make it work at least for samples, which do not need BlazorWebView, so that's why I've tried to add UsingMicrosoftNETSdkRazor condionally, depending on the platform.

Seems like I've broken those samples for other platforms though))

**Comment by Dreamescaper** [comment]
I have fixed the workaround for ios - now it doesn't break BlazorWebView projects for Android.

I have moved the PR to Ready For Review - not everything is working, but mostly on MAUI side, and could be tackled separately.

I haven't migrated all the samples, as I'm not sure is it makes sense. Some of them target specifically BlazorWebView. Weather sample uses PancakeView controls, which are not supported anymore.

I have updated Microsoft.MobileBlazorBindings.Authentication and Microsoft.MobileBlazorBindings.Authentication.Msal projects, but I'm not really familiar with them, and not sure whether they are still needed here.

Note that I haven't deleted all the staff that is not migrated to MAUI (samples, WebView projects), but simply removed from the solution, as I wasn't sure whether any remaining items are still actual.

**Comment by Dreamescaper** [comment]
CI fails, but I can't see the details why.

**Comment by Dreamescaper** [comment]
If anyone would like to check it out and leave feedback, you can use this temporary nuget source: 
https://www.myget.org/F/dreamescaper/api/v3/index.json

<details>
<summary>Details</summary>

1. You need to create a file `nuget.config` with the following content:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="mobileblazorbindings-maui-preview" value="https://www.myget.org/F/dreamescaper/api/v3/index.json" />
  </packageSources>
</configuration>
```

2. Install MBB templates:
`dotnet new -i Microsoft.MobileBlazorBindings.Templates::0.7.5-preview-maui-g50f54e2613`

3. Create a project from template:
`dotnet new mobileblazorbindings -o FirstMobileBlazorBindingsApp`

</details>

**Comment by Dreamescaper** [comment]
Hi @Eilon!
MAUI has reached RC phase, so I'd like to ping about the status of this PR and the project overall.
Are there any plans to keep this repo moving forward?
I really like this library, I use it for my projects, and I plan to work on it further in the nearby future.

If it can't be supported here, I'm thinking about forking it, and continuing working on that separately (at least until it is supported).
Any other options (like moving it to CommunityToolkit or smth like that, not sure) ?

**Comment by Dreamescaper** [comment]
I have forked this repository and published to nuget (renamed to BlazorBindings.Maui).
You can read more [here](https://dreamescaper.github.io/MobileBlazorBindingsDocs/maui-blazor-bindings/release-notes/preview-6.html).
If at any point of time Microsoft developers decide to push this repository moving forward, I'll gladly contribute all of my changes here.

**Comment by Eilon** [comment]
I'm taking a crack at this 😁 

image

**Comment by Dreamescaper** [comment]
@Eilon Yeah, just run "git clean -fdx" with your VS closed. It doesn't like remains of pre-MAUI samples parts.

**Comment by Eilon** [comment]
Ah, `git clean -xdf` and a rebuild got me past that! My CPU is still on fire, though!

> ========== Build: 16 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

image

**Comment by Eilon** [comment]
Well, so far it's working quite fine! I think I hit a few issues but I can't tell if it's an MBB issue or a MAUI issue.

**Comment by Eilon** [comment]
I think the only real issue I've hit so far is this exception: https://github.com/Dreamescaper/BlazorBindings.Maui/blob/maui/src/Microsoft.MobileBlazorBindings/Elements/Handlers/ModalContainerHandler.cs#L84-L85

To repro:

1. Run MBB ToDo sample on Windows/Android (didn't try Apple platforms yet)
2. Make sure there's at least one item in the list
3. Click the "..." button next to one of the todo items to launch the "modal" dialog
4. Press either Save or Cancel (anything to dismiss the "modal"

Result:

```
{System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.MobileBlazorBindings.Elements.Handlers.ModalContainerHandler.RemoveChild(Element child) in C:\GitHub\MobileBlazorBindings\src\Microsoft.MobileBlazorBindings\Elements\Handlers\ModalContainerHandler.cs:line 85
   at Microsoft.MobileBlazorBindings.MobileBlazorBindingsElementManager.RemoveChildElement(IMauiElementHandler parentHandler, IMauiElementHandler childHandler) in C:\GitHub\MobileBlazorBindings\src\Microsoft.MobileBlazorBindings\MobileBlazorBindingsElementManager.cs:line 79
   at Microsoft.MobileBlazorBindings.Core.ElementManager`1[[Microsoft.MobileBlazorBindings.IMauiElementHandler, Microsoft.MobileBlazorBindings, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null]].RemoveChildElement(IElementHandler parentHandler, IElementHandler childHandler) in C:\GitHub\MobileBlazorBindings\src\Microsoft.MobileBlazorBindings.Core\ElementManagerOfElementType.cs:line 45
   at Microsoft.MobileBlazorBindings.Core.NativeComponentAdapter.RemoveSelfAndDescendants() in C:\GitHub\MobileBlazorBindings\src\Microsoft.MobileBlazorBindings.Core\NativeComponentAdapter.cs:line 134
   at Microsoft.MobileBlazorBindings.Core.NativeComponentAdapter.RemoveSelfAndDescendants() in C:\GitHub\MobileBlazorBindings\src\Microsoft.MobileBlazorBindings.Core\NativeComponentAdapter.cs:line 141
   at Microsoft.MobileBlazorBindings.Core.NativeComponentAdapter.ApplyRemoveFrame(Int32 siblingIndex) in C:\GitHub\MobileBlazorBindings\src\Microsoft.MobileBlazorBindings.Core\NativeComponentAdapter.cs:line 125
   at Microsoft.MobileBlazorBindings.Core.NativeComponentAdapter.ApplyEdits(Int32 componentId, ArrayBuilderSegment`1 edits, ArrayRange`1 referenceFrames, RenderBatch batch, HashSet`1 processedComponentIds) in C:\GitHub\MobileBlazorBindings\src\Microsoft.MobileBlazorBindings.Core\NativeComponentAdapter.cs:line 66
   at Microsoft.MobileBlazorBindings.Core.NativeComponentRenderer.UpdateDisplayAsync(RenderBatch& renderBatch) in C:\GitHub\MobileBlazorBindings\src\Microsoft.MobileBlazorBindings.Core\NativeComponentRenderer.cs:line 102
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()}
    base: {System.SystemException}
```

Expected:
No exception.


To be honest, everything about how modals are implemented in MBB is quite hacky. I'm sure there's some good code in there, but I don't know where 😄 I wouldn't have this prevent me from merging the PR, but rather I'd log it as a separate issue to investigate.

**Comment by Eilon** [comment]
BTW this code didn't change as part of this PR, so it might be caused by some other change in this PR, or a change in .NET MAUI.

**Comment by Dreamescaper** [comment]
I think it is fine simply to remove throwing that exception, make it no-op. But yeah, I planned to rework dealing with modals anyway (or rather cleanup some parts that I already have). I've drafted a small proposal here: https://github.com/dotnet/MobileBlazorBindings/issues/421 .

**Comment by Eilon** [comment]
Yeah without the exception it seems to just work fine 😄

**Comment by Eilon** [comment]
Aside from iOS/macOS testing, is there anything else you think needs to be done before merging? I've reviewed a lot of the code so far and I think it's good, but I will finish reviewing first anyway.

**Comment by Eilon** [comment]
Another thing I noticed is that the Component Generator doesn't copy doc comments anymore. We'll definitely want to bring that back, but it might need to work a bit differently due to how the MAUI packages are created (but as of MAUI GA they XML files at least _exist_).

**Comment by Eilon** [comment]
Well, it's merged! 🥳

**Comment by dcuccia** [comment]
Wonderful, can't wait to try it out!

**Pull request merged**
